### ISSUE TITLE
[Feature] Force remove classes (the ones that ARE being used)

### ISSUE THREAD

**Issue by lexdubyna** [FullHuman/purgecss#419] opened 2020-05-22 09:53 UTC
### Why?
I am currently working on a php website, that utilizes webpack, postcss and tailwindcss. I have multiple parts of the front-end that are being loaded dynamically (js and css). I was able to split tailwindcss build for dynamic files, but if a file has classes, that have previously been loaded on the page, I can't force purge them in my dynamic files. Why do I want this? Well, basically that is what client wants, because "page load speed is top priority" so NO unused css and js code should be present on initial page load. Agree to disagree, but I think an option like this could be beneficial in some cases.
```
force: ['container', 'flex'],
forcePatterns: [/flex$/]
```

**Comment by Ffloriel** [comment] 2020-06-13 14:04
duplicate of https://github.com/FullHuman/purgecss/issues/302

**Closed by Ffloriel** 2020-06-13 14:04 UTC
