### ISSUE TITLE
Purgecss break with Tailwind and Vuetify

### ISSUE THREAD

**Issue by ronssij** [FullHuman/purgecss#360] opened 2020-04-10 06:21 UTC
some of the classes are purged incorrectly. I have this postcss config on my project.

>  @fullhuman/postcss-purgecss": "^2.1.2"

`const purgecss = require('@fullhuman/postcss-purgecss')({

  // Specify the paths to all of the template files in your project
  content: [
    './src/**/*.html',
    './src/**/*.vue',
    './src/**/*.jsx',
    './node_modules/vuetify/**/*.js'
  ],

  // Include any special characters you're using in this regular expression
  defaultExtractor: content => content.match(/[\w-/:]+(?<!:)/g) || []
})

module.exports = {
  plugins: [
    require('tailwindcss'),
    require('autoprefixer'),
    ...process.env.NODE_ENV === 'production'
      ? [purgecss]
      : [purgecss]
  ]
}
`
some of the classes are missing

**Comment by pnlinh-it** [comment] 2020-04-10 15:51
I also face this issue,  some html tag such as input, button style are removed.

**Comment by TheDutchCoder** [comment] 2020-04-17 12:55
I'm fairly sure this is not related to Vuetify, but only the purgeCSS/Tailwind combo as we face the same issue and we don't use Vuetify (but do use Tailwind).

For some reason it seems to no longer parse our phtml files.

**Comment by NicholasBertazzon** [comment] 2020-04-25 16:50
I'm using the postbuild cli command (React app) and it actually erase everything from tailwind css, from 950KB to 1KB

**Comment by JKodev** [comment] 2020-05-07 14:20
@NicholasBertazzon actually, tailwindcss has a purge action inside her code for optimize the bundle size. check https://tailwindcss.com/docs/controlling-file-size#removing-unused-css

**Comment by NicholasBertazzon** [comment] 2020-05-07 15:33
@JKodev Yeah I tried it some days ago, togheter with craco on react works so nice, I'm not using the cli version anymore

**Comment by Ffloriel** [comment] 2020-12-14 00:13
closing as the issue is not present when using tailwindcss built-in purgecss.

**Closed by Ffloriel** 2020-12-14 00:13 UTC
