### ISSUE TITLE
Css attribute selectors [Request]

### ISSUE THREAD

**Issue by yinx** [FullHuman/purgecss#30] opened 2017-11-27 10:51 UTC
I can't seem to find a way to get purgecss to work with css selectors like [class*="section-"] or [title~="flower"].

Is there a method I'm overlooking or if not, is there a way to implement this?

**Comment by pxwee5** [comment] 2017-12-01 00:11
```
new PurgecssPlugin({
  whitelistPatterns: [new RegExp('frame')]
})
```
This will match all selectors and classes that has `frame`. For v0.13.1. 
See [here](https://github.com/FullHuman/purgecss/blob/master/src/index.js#L335)

**Comment by Ffloriel** [comment] 2017-12-02 11:35
There is no method to implement this but as @pxwee5 pointed out, you can specified regex to tell purgecss to not remove some selectors. See [here](https://www.purgecss.com/whitelisting.html)

**Comment by pxwee5** [comment] 2017-12-03 20:56
The `whitelistPatterns` only checks for [class*=`classes`] (and different types of selectors). 

@Ffloriel, is there a way to check for the entire thing? `[class*=classes]` or is it not necessary at all? What if I want to whitelist all css class selectors?

**Comment by Ffloriel** [comment] 2017-12-05 07:58
I see, I think what you need is to define a custom extractor. Check this [gist](https://gist.github.com/reinink/83058f9af402aa474010844f7f2b1c54) for using purgecss with tailwindcss
Let me know if it solves the problem.

**Comment by pxwee5** [comment] 2017-12-05 20:23
According to my tests and from what I found out, a custom extractor is for custom extraction of the glob files, not the CSS files. Let me know if I'm wrong.

**Comment by Ffloriel** [comment] 2017-12-05 21:28
By default, selectors like `md:w-3/12` are not extracted from the files (because of the characters `:` and `/`). So purgecss will not see those as used and will remove them from the css files.

**Comment by pxwee5** [comment] 2017-12-06 08:21
Correct me if I'm wrong. Are you saying that the custom extractor will extract strings from both the css and the html files?

**Comment by Ffloriel** [comment] 2017-12-06 12:58
No. Extractors are used to extract selectors from content files (html, pug, ...)
If you have the following css:
```css
w-6/12 {
    color: green;
}
md:w-3/12 {
    color: blue;
}
```
and an html file:
```html
<div class="flexgrid">
  <div class="w-6/12 md:w-3/12">Content<div>
  <div class="w-6/12 md:w-3/12">Content<div>
<div>
```

First, purgecss will use an extractor to determine which selectors are used. The default extractor will considered `div`, `flexgrid` but not `w-6/12` or `md:w-3/12`.
Then, purgecss will go through the css file, look at each selector in it and simply look if the selector is also in the content files. If it's not, the css is removed. In this example with the default extractor, `w-6/12` and `md:w-3/12` will be removed.

**Comment by pxwee5** [comment] 2017-12-06 20:57
Thanks for explaining and trying to help. However I still couldn't get the extractor to work. I don't think the extractor reads the CSS file (I did a console.dir in the extractor to confirm that). 

What I am trying to do here is to get PurgeCSS to read not allow both of the following classes to pass:
.css
```
.flexgrid {}
.flexgrid>[class*=w-] {}
```

Because the usage of this is just simply using the `.flexgrid` on any div and no extra classes is set to its child. 
.html
```
<div class="flexgrid">
  <div class="">Content<div>
  <div class="">Content<div>
<div>
```

So with this html, the extractor will only pick up the flexgrid class. And after comparing it with the css file above, only `.flexgrid {}` gets through. The one with a child selector gets removed.

**Comment by Ffloriel** [comment] 2017-12-06 22:24
Thanks for the clarification. I understand the problem now.
Purgecss does not behave as expected with attribute selectors. It should leave the attributes selectors in the css. I will look into it and release a new version when the issue is fixed

**Comment by Ffloriel** [comment] 2017-12-07 19:17
The issue should be fix in v0.14.0. Let me know if you found any issues with it.

**Comment by pxwee5** [comment] 2017-12-07 20:24
Will this only work under `legacy: true`? In my tests, the legacy option will not read numbers and some symbols and is quite inaccurate. The PurgeCSS (non-legacy) option is much cleaner and I think this bug should be fixed for both legacy and without. 

What do you think?

**Comment by Ffloriel** [comment] 2017-12-07 20:39
It should work for both. 
The `legacy` option was meant to provide a similar result as purifycss when purgecss was in an early stage. The option will be removed with the 1.0.0 version.

**Comment by pxwee5** [comment] 2017-12-07 21:31
Hmm, tested it and somehow it didn't work unless `legacy: true` is set. 
```
.flexgrid {
  @apply .flex .flex-wrap .-mx-4 .-mb-8;

  & > *[class*='w-'] {
    @apply .px-4 .pb-8
  }
}
```

Output
```
.flexgrid{display:-webkit-box;display:-ms-flexbox;display:flex;-ms-flex-wrap:wrap;flex-wrap:wrap;margin-left:-1rem;margin-right:-1rem;margin-bottom:-2rem}@supports(display:-ms-grid){}
```

The test in the test folder had `legacy: true` set I think.

**Comment by Ffloriel** [comment] 2017-12-07 21:44
There are tests for both with and without `legacy`.
Could you create a repo that reproduce the issue? It will be easier for me to look at the issue that way.

**Comment by pxwee5** [comment] 2017-12-07 22:25
Hey @Ffloriel. Here's the repo. 
https://github.com/pxwee5/test-purgecss/

**Comment by Ffloriel** [comment] 2017-12-07 23:08
@pxwee5 thank you very much.

**Comment by Ffloriel** [comment] 2017-12-07 23:13
_gulp-purgecss_ was still using the v0.13.0. _gulp-purgecss_ version is now aligned with purgecss.
The output is
```css
.flexgrid {
  background-color: black
}

.flexgrid[class*=w] {
  background-color: blue;
}

.flexgrid>*[class*=w-] {
  background-color: yellow;
}
```

**Comment by pxwee5** [comment] 2017-12-07 23:22
Gah. That was it! Didn't know I have to upgrade the bundler plugins as well. 
Working great now! Thanks alot!

**Closed** 2017-12-07 23:32 UTC
Labels: bug

**Comment by stevenmunro** [comment] 2019-02-26 10:21
Sorry to reopen this issue. I'm trying to get every classname that is a child of ".app" whitelisted. Is there a way to do that?

For example.

.app .form
.app .this-div
.app .overlay

I don't want to whitelist each and every internal class. But they are all children of .app.
