### ISSUE TITLE
White List a Specific File for php rendered content

### ISSUE THREAD

**Issue by myleshyson** [FullHuman/purgecss#38] opened 2018-01-03 17:52 UTC
I'm referencing this issue here because I didn't see a clear answer. #35
Is there a way to whitelist specific files? It would be helpful to do this since I use this plugin for WordPress themes and need to white list classes for content generated by plugins or widgets. Thanks.

**Comment by Ffloriel** [comment] 2018-01-04 23:52
There is no option to whitelist specific css files but you can specified your css files with `css`.
`css` takes a glob or a list of files. If you don't want some css files to be included, I would suggest using [glob-all](https://www.npmjs.com/package/glob-all) to get the list of files.
It can be something similar to the example below.
```js
const files = glob.sync([
  '**/*.css',      //include css files
  '!css/whitelist/',   //then, exclude   css/whitelist/ 
])
```

Let me know if this is what you were looking for.

**Comment by myleshyson** [comment] 2018-01-10 17:44
Hey thanks for responding. Not exactly since I'm using the webpack version, I can't use the css option. Right now my build setup is using Laravel Mix.

**Comment by Ffloriel** [comment] 2018-01-11 12:47
I see. There is no official way to whitelist a file at the moment but there is some possible solutions on the [purgecss webpack repo](https://github.com/FullHuman/purgecss-webpack-plugin).

I am closing this issue as it's a duplicate of this https://github.com/FullHuman/purgecss-webpack-plugin/issues/3

**Closed by Ffloriel** 2018-01-11 12:47 UTC

**Comment by leveloid** [comment] 2018-05-15 01:09
@Ffloriel Another use case I ran into:

Using a package like (https://github.com/utatti/perfect-scrollbar) where the css is unused until a js element is added to the page.

I want to whitelist the file with the necessary CSS, but am forced to prepend all the classes. (In this case, the package's classes are already prepended, but this isn't the case usually)
