### ISSUE TITLE
Ability to collect the rejected CSS

### ISSUE THREAD

**Issue by Timkor** [FullHuman/purgecss#553] opened 2020-12-24 06:59 UTC
I am running PurgeCSS while generating html pages. It will purge an inline style tag in the head containing the ciritical CSS. However I would like to inject the non-critical css in a later stage (when the browser is idle).

I am able to get the `rejected` selectors. But I did not found a way to collect the rejected CSS by using these selectors.

Could this feature be build in?

This should not change current behaviour.

**Comment by Ffloriel** [comment] 2021-01-17 20:59
There's currently no plan to add this feature. Closing as it is a duplicate of #131

**Closed by Ffloriel** 2021-01-17 20:59 UTC
