### ISSUE TITLE
Cannot find module '@fullhuman/vue-cli-plugin-purgecss'

### ISSUE THREAD

**Issue by alu0100536652** [FullHuman/purgecss#374] opened 2020-04-14 20:15 UTC
I have a problem adding purgecss to my vue project using vue CLI. I have added it using the CLI and when making a serve or build it fails.

```
$ vue-cli-service build --mode production --dest dist --target app --dashboard
internal/modules/cjs/loader.js:582
    throw err;
    ^

Error: Cannot find module '@fullhuman/vue-cli-plugin-purgecss'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:580:15)
    at Function.Module._load (internal/modules/cjs/loader.js:506:25)
    at Module.require (internal/modules/cjs/loader.js:636:17)
    at require (internal/modules/cjs/helpers.js:20:18)

```

NPM Version: 6.14.4
Node Version: 10.14.1
Vue CLI Version: 4.2.3
OS: MacOS Catalina

**Comment by kashirin-dm** [comment] 2020-04-20 11:07
Duplicate of #359

**Closed** 2020-04-20 18:07 UTC
