### ISSUE TITLE
Ouput to a specific file

### ISSUE THREAD

**Issue by mrmowji** [FullHuman/purgecss#373] opened 2020-04-13 17:47 UTC
I'm trying to output the result of PurgeCSS to specific file, but the `--ouput` argument or `output` property seems to accept only directories:
```js
module.exports = {
  // other options
  output: ["src/assets/css/site.css"],
  // other options
};
```
```bash
purgecss --config ./purgecss.config.js --output ./src/assets/css/site.css
```
I'm using Ubuntu 18.4, Node 12.16.1, and PurgeCSS 2.1.2.

**Why this is needed**
Suppose I have a `site.unpurged.css` file which I want to purge and then minify. If I use PurgeCSS, I must specify another directory for the output and then minify the file inside the second folder. That'd be much better to have all these CSS files in one folder; `site.unpurged.css`, then `site.css`, and then `site.min.css`.

**Comment by Ffloriel** [comment] 2020-04-20 23:09
Will be useful indeed. I'll look into it.
I'm closing this issue as it's a duplicate of https://github.com/FullHuman/purgecss/issues/264

**Closed by Ffloriel** 2020-04-20 23:09 UTC
